name: on_audio_edit
description: Flutter Plugin used to edit and read audios/songs infos/tags [Mp3, OggVorbis, Wav, etc...].
version: 1.5.13
homepage: https://github.com/nbtpApp/on_audio_edit
# pub.dev: https://pub.dev/packages/on_audio_query
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ^3.5.0 #'>=2.12.0 <3.0.0'
  flutter: '>=3.3.0' #">=1.20.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^4.0.0 #^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.lucasjosino.on_audio_edit
        pluginClass: OnAudioEditPlugin
#      ios:
#        pluginClass: OnAudioEditPlugin
